apiVersion: v1
kind: Service
metadata:
  name: pdd-nagoya
spec:
  type: NodePort
  selector:
    app: pdd-nagoya
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30001